// Application-level TypeScript types.
// Database types are in src/types/database.ts (generated by Supabase CLI).

export type ApplicationStatus =
  | 'draft'
  | 'applied'
  | 'screening'
  | 'interviewing'
  | 'offer'
  | 'negotiating'
  | 'accepted'
  | 'rejected'
  | 'withdrawn';

export type CalendarItemKind = 'task' | 'event' | 'meeting' | 'interview';

export type AutomationTriggerType =
  | 'application_status_changed'
  | 'application_created'
  | 'interview_scheduled'
  | 'task_due_soon';

export type AutomationActionType = 'send_email' | 'create_task' | 'update_application_status';

export type SectionType =
  | 'contact_info'
  | 'summary'
  | 'work_experience'
  | 'education'
  | 'skills'
  | 'certifications'
  | 'custom';

// ResumeContentV1 and CoverLetterContentV1 are defined in docs/technical-spec/content-model.md
// and will be fleshed out in Phase 4.
export interface ResumeContentV1 {
  version: 1;
  sections: ResumeSection[];
}

export interface ResumeSection {
  id: string;
  type: SectionType;
  order: number;
  data: unknown;
}

export interface CoverLetterContentV1 {
  version: 1;
  body: string;
}
